# =============================================================================
# Logger
# =============================================================================
"""
Triple-channel logger: console table + metrics.csv + WandB.

WandB is optional — if wandb is not installed or login fails, the logger
falls back silently to console + CSV only. All existing behaviour is preserved.

Usage in main.py:
    logger = Logger(run_name, total_epochs, runs_dir, config=cfg)
    for epoch in range(total_epochs):
        logger.epoch_start()
        train_metrics = train_one_epoch(...)
        eval_metrics  = evaluate(...)
        logger.log_epoch(epoch, train_metrics, eval_metrics)
        if logger.is_best():
            torch.save(model.state_dict(), logger.best_ckpt_path)
    logger.summary()

Output layout:
    runs/<run_name>/
    ├── metrics.csv      one row per epoch — all metrics including th_* and grad_*
    ├── best_model.pth   saved by main.py when logger.is_best() is True
    └── plots/           generated by plot.py — kept alongside WandB curves

WandB dashboard mirrors exactly what plot.py generates locally:
    - Triplet Loss
    - Rank-1 / mAP vs 36% baseline
    - Active Triplets %
    - Learning Rate
    - Embedding Distances (d_pos, d_neg, gap)
    - Gradient Norms (global + per block)

See: engine/train.py    — produces train_metrics (core + th_* + grad_*)
See: engine/evaluate.py — produces eval_metrics
See: plot.py            — reads metrics.csv and generates local PNG plots
"""

import os
import csv
import time
from typing import Optional

# =============================================================================
# WandB — optional import, graceful fallback if not installed / not logged in
# =============================================================================
try:
    import wandb
    _WANDB_AVAILABLE = True
except ImportError:
    _WANDB_AVAILABLE = False

# =============================================================================
# ANSI — terminal only, never written to CSV or WandB
# =============================================================================
_RESET  = "\033[0m"
_BOLD   = "\033[1m"
_GREEN  = "\033[92m"
_YELLOW = "\033[93m"
_CYAN   = "\033[96m"
_RED    = "\033[91m"
_DIM    = "\033[2m"

def _g(s): return f"{_GREEN}{s}{_RESET}"
def _y(s): return f"{_YELLOW}{s}{_RESET}"
def _r(s): return f"{_RED}{s}{_RESET}"
def _c(s): return f"{_CYAN}{s}{_RESET}"
def _b(s): return f"{_BOLD}{s}{_RESET}"
def _d(s): return f"{_DIM}{s}{_RESET}"

# AIC21 2021 baseline — used for color coding in console + WandB annotations
BASELINE_MAP = 0.36

# Core columns always present — th_* and grad_* appended dynamically on epoch 0
CORE_COLUMNS = [
    "epoch", "loss", "active_triplets", "lr",
    "rank1", "mAP", "epoch_time_s",
]


class Logger:
    """
    Logs training metrics to console, metrics.csv, and WandB.

    WandB integration is additive — all existing console and CSV behaviour
    is preserved exactly. WandB adds a live remote dashboard that mirrors
    the local plot.py curves so both can be compared side by side.

    metrics.csv columns:
      - Core  : epoch, loss, active_triplets, lr, rank1, mAP, epoch_time_s
      - th_*  : triplet health (added automatically when present in train_metrics)
      - grad_*: gradient norms (added automatically when present in train_metrics)

    WandB panels (auto-created):
      - train/loss          — triplet loss per epoch
      - train/active_pct    — active triplet fraction [0, 1]
      - train/lr            — learning rate
      - eval/rank1          — Rank-1 retrieval accuracy
      - eval/mAP            — mean Average Precision vs 36% baseline
      - triplet/d_pos       — mean anchor-positive distance
      - triplet/d_neg       — mean anchor-negative distance
      - triplet/gap         — d_neg - d_pos (should be > margin)
      - grad/global         — global gradient norm
      - grad/block_*        — per-block gradient norms

    Attributes:
        run_dir        : str   — runs/<run_name>/
        csv_path       : str   — runs/<run_name>/metrics.csv
        best_ckpt_path : str   — runs/<run_name>/best_model.pth
        best_mAP       : float — running best mAP across all epochs
        wandb_enabled  : bool  — True if WandB was initialised successfully
    """

    def __init__(
        self,
        run_name:     str,
        total_epochs: int,
        runs_dir:     str = "runs",
        config:       Optional[dict] = None,   # full cfg dict from tiny_vit.yaml
    ):
        self.run_name     = run_name
        self.total_epochs = total_epochs
        self.run_dir      = os.path.join(runs_dir, run_name)

        os.makedirs(self.run_dir, exist_ok=True)

        self.csv_path       = os.path.join(self.run_dir, "metrics.csv")
        self.best_ckpt_path = os.path.join(self.run_dir, "best_model.pth")

        self._best_mAP:    float           = 0.0
        self._is_best:     bool            = False
        self._t_start:     Optional[float] = None
        self._csv_columns: list[str]       = []

        # ── WandB init ────────────────────────────────────────────────────────
        self.wandb_enabled = False
        if _WANDB_AVAILABLE:
            try:
                wandb.init(
                    project = "vehicle-reid",
                    name    = run_name,
                    config  = config or {},
                    # resume="allow" lets you continue a crashed run
                    resume  = "allow",
                    dir      = config.get("monitoring", {}).get("wandb_dir", "wandb_runs"),
                )
                # define custom x-axis for all panels
                wandb.define_metric("epoch")
                wandb.define_metric("train/*",   step_metric="epoch")
                wandb.define_metric("eval/*",    step_metric="epoch")
                wandb.define_metric("triplet/*", step_metric="epoch")
                wandb.define_metric("grad/*",    step_metric="epoch")

                # horizontal baseline line on the mAP panel
                wandb.define_metric(
                    "eval/mAP_baseline",
                    step_metric = "epoch",
                )

                self.wandb_enabled = True
                print(f"  WandB  : {_g('enabled')}  →  {wandb.run.url}")
            except Exception as e:
                print(f"  WandB  : {_y('disabled')} ({e})")

        self._print_banner()

    # =========================================================================
    # Public API
    # =========================================================================

    def epoch_start(self) -> None:
        """Call at the top of each epoch — starts the chronometer."""
        self._t_start = time.time()

    def log_epoch(
        self,
        epoch:         int,
        train_metrics: dict,
        eval_metrics:  dict,
    ) -> None:
        """
        Logs one epoch to console, CSV, and WandB.

        Args:
            epoch         : current epoch index (0-based)
            train_metrics : dict from train_one_epoch()
            eval_metrics  : dict from evaluate() — {"rank1", "mAP"} or {}
        """
        epoch_time = time.time() - self._t_start if self._t_start else float("nan")

        # ── build flat row ────────────────────────────────────────────────────
        row: dict = {
            "epoch":           epoch,
            "loss":            train_metrics.get("loss",            float("nan")),
            "active_triplets": train_metrics.get("active_triplets", float("nan")),
            "lr":              train_metrics.get("lr",              float("nan")),
            "rank1":           eval_metrics.get("rank1",            float("nan")),
            "mAP":             eval_metrics.get("mAP",              float("nan")),
            "epoch_time_s":    epoch_time,
        }
        for key, val in train_metrics.items():
            if key.startswith("th_") or key.startswith("grad_"):
                row[key] = val

        # ── best mAP tracking ────────────────────────────────────────────────
        mAP = row["mAP"]
        if mAP == mAP and mAP > self._best_mAP:   # nan-safe
            self._best_mAP = mAP
            self._is_best  = True
        else:
            self._is_best  = False

        # ── console + CSV (unchanged) ─────────────────────────────────────────
        self._print_row(row)
        self._write_csv(row)

        # ── WandB log ─────────────────────────────────────────────────────────
        if self.wandb_enabled:
            self._log_wandb(epoch, row)

    def is_best(self) -> bool:
        """True if the last logged epoch set a new best mAP."""
        return self._is_best

    @property
    def best_mAP(self) -> float:
        """Running best mAP across all logged epochs."""
        return self._best_mAP

    def log_message(self, msg: str) -> None:
        """Prints a timestamped info message — checkpoints, warnings, etc."""
        print(f"{_d(time.strftime('%H:%M:%S'))}  {_c('ℹ')}  {msg}")

    def summary(self) -> None:
        """Prints a final summary banner and closes the WandB run."""
        beat = (_g("✓ beats 36% baseline") if self._best_mAP >= BASELINE_MAP
                else _r("✗ below 36% baseline"))
        w = 62
        print()
        print(_b(f"┌{'─'*w}┐"))
        print(_b(f"│{'Training Complete':^{w}}│"))
        print(_b(f"├{'─'*w}┤"))
        print(_b(f"│  Best mAP : {self._best_mAP:.4f}  {beat:<{w-24}}│"))
        print(_b(f"│  CSV      : {self.csv_path:<{w-13}}│"))
        print(_b(f"│  Ckpt     : {self.best_ckpt_path:<{w-13}}│"))
        print(_b(f"└{'─'*w}┘"))
        print()

        if self.wandb_enabled:
            # log best mAP as a summary metric visible on WandB project page
            wandb.summary["best_mAP"]  = self._best_mAP
            wandb.summary["beats_baseline"] = self._best_mAP >= BASELINE_MAP
            wandb.finish()

    def __repr__(self) -> str:
        return (f"Logger(run='{self.run_name}', "
                f"epochs={self.total_epochs}, "
                f"best_mAP={self._best_mAP:.4f}, "
                f"wandb={self.wandb_enabled})")

    # =========================================================================
    # Private — WandB
    # =========================================================================

    def _log_wandb(self, epoch: int, row: dict) -> None:
        """
        Sends one epoch of metrics to WandB with clean panel names.

        Panel structure mirrors plot.py:
            train/   — loss, active_pct, lr
            eval/    — rank1, mAP, mAP_baseline (constant 0.36 reference line)
            triplet/ — d_pos, d_neg, gap, collapse
            grad/    — global + per-block norms
        """
        def _valid(v) -> bool:
            """True if v is a real number (not nan, not bool)."""
            return isinstance(v, (int, float)) and v == v and not isinstance(v, bool)

        log: dict = {"epoch": epoch}

        # ── train panel ───────────────────────────────────────────────────────
        if _valid(row.get("loss")):
            log["train/loss"]       = row["loss"]
        if _valid(row.get("active_triplets")):
            log["train/active_pct"] = row["active_triplets"] * 100   # % for readability
        if _valid(row.get("lr")):
            log["train/lr"]         = row["lr"]

        # ── eval panel ────────────────────────────────────────────────────────
        if _valid(row.get("rank1")):
            log["eval/rank1"]         = row["rank1"]
        if _valid(row.get("mAP")):
            log["eval/mAP"]           = row["mAP"]
            log["eval/mAP_baseline"]  = BASELINE_MAP   # constant reference line

        # ── triplet health panel ──────────────────────────────────────────────
        if _valid(row.get("th_mean_d_pos")):
            log["triplet/d_pos"]    = row["th_mean_d_pos"]
        if _valid(row.get("th_mean_d_neg")):
            log["triplet/d_neg"]    = row["th_mean_d_neg"]
        if _valid(row.get("th_gap")):
            log["triplet/gap"]      = row["th_gap"]
        if "th_collapse" in row:
            log["triplet/collapse"] = int(row["th_collapse"])   # 0/1 for WandB

        # ── gradient norms panel ─────────────────────────────────────────────
        if _valid(row.get("grad_norm_global")):
            log["grad/global"] = row["grad_norm_global"]
        for key, val in row.items():
            if key.startswith("grad_norm_") and key != "grad_norm_global":
                panel_name = key.replace("grad_norm_", "grad/")   # grad/blocks.0
                if _valid(val):
                    log[panel_name] = val

        wandb.log(log, step=epoch)

    # =========================================================================
    # Private — console + CSV (unchanged from original)
    # =========================================================================

    def _print_banner(self) -> None:
        w = 62
        print()
        print(_b(f"┌{'─'*w}┐"))
        print(_b(f"│{'VehicleViT — Training':^{w}}│"))
        print(_b(f"├{'─'*w}┤"))
        print(_b(f"│  Run    : {self.run_name:<{w-11}}│"))
        print(_b(f"│  Epochs : {self.total_epochs:<{w-11}}│"))
        print(_b(f"│  CSV    : {self.csv_path:<{w-11}}│"))
        print(_b(f"└{'─'*w}┘"))
        print()
        hdr = (f"{'Epoch':>8}  {'Loss':>8}  {'Active%':>8}  "
               f"{'LR':>10}  {'Rank-1':>8}  {'mAP':>8}  {'Time(s)':>8}")
        sep = _d("─" * len(hdr))
        print(sep); print(_d(hdr)); print(sep)

    def _print_row(self, row: dict) -> None:
        loss   = row["loss"]
        active = row["active_triplets"]
        lr     = row["lr"]
        rank1  = row["rank1"]
        mAP    = row["mAP"]
        t      = row["epoch_time_s"]

        def _loss(v):
            if v != v: return _d(f"{'nan':>8}")
            return (_r if v > 0.5 else _y if v > 0.1 else _g)(f"{v:8.4f}")

        def _active(v):
            if v != v: return _d(f"{'nan':>8}")
            p = v * 100
            return (_r if v < 0.05 else _y if v > 0.80 else _g)(f"{p:7.1f}%")

        def _metric(v):
            if v != v: return _d(f"{'—':>8}")
            return (_g if v >= BASELINE_MAP else _y)(f"{v:8.4f}")

        lr_str = f"{lr:>10.2e}" if lr == lr else f"{'nan':>10}"
        t_str  = f"{t:>8.1f}"   if t  == t  else f"{'nan':>8}"

        print(
            f"{row['epoch']+1:3d}/{self.total_epochs}  "
            f"{_loss(loss)}  {_active(active)}  "
            f"{lr_str}  "
            f"{_metric(rank1)}  {_metric(mAP)}  "
            f"{t_str}  "
            f"{_c(_b('★ best')) if self._is_best else '      '}"
        )

    def _write_csv(self, row: dict) -> None:
        if not self._csv_columns:
            self._csv_columns = CORE_COLUMNS + [
                k for k in row if k not in CORE_COLUMNS
            ]
            with open(self.csv_path, "w", newline="") as f:
                csv.DictWriter(f, fieldnames=self._csv_columns).writeheader()

        formatted = {
            k: (f"{v:.6f}" if isinstance(v, float) and v == v
                else ("nan" if isinstance(v, float) else v))
            for k, v in row.items()
        }
        with open(self.csv_path, "a", newline="") as f:
            csv.DictWriter(
                f, fieldnames=self._csv_columns, extrasaction="ignore"
            ).writerow(formatted)